[package]
name = "farming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy-inspector-egui = "0.19.0"
bevy = "0.11"
hashbrown = "0.14.0"
pathfinding = "4.3.2"
futures-lite = "1.13.0"